check tests for FAIL instead of diffing results
Signed-off-by: Jiri Jaburek <comps@nomail.dom>

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -22,7 +22,10 @@ export LD_LIBRARY_PATH="$PWD/bin"
 export TEST_BINDIR="$PWD/bin"
 
 function run_arg {
-	local variant="$1" test="$2" binary=
+	local testpath="$1" binary=
+
+	local variant= test=
+	IFS=/ read -r variant test <<<"${testpath#/}"
 
 	for binary in ptef-runner ptef-report ptef-mklog libptef.so.0.0; do
 		if [ ! -x "bin/$variant/$binary" ]; then
@@ -70,47 +73,31 @@ fi
 
 rm -f valgrind.log
 
-declare -A variants_used
+exec {results_fd}>"results.log"
 for testpath in "${variants[@]}"; do
-	variant= test=
-	IFS=/ read -r variant test <<<"${testpath#/}"
-	variants_used["$variant"]=1
-
-	exec {results_fd}>"results/cur-$variant.list"
-	PTEF_RESULTS_FD="$results_fd" run_arg "$variant" "$test"
-	exec {results_fd}>&-
+	PTEF_RESULTS_FD="$results_fd" run_arg "$testpath"
 done
+exec {results_fd}>&-
 
-# when running a full test set (without args),
-# compare generated results to a known-good reference
-diffcolor=$(if diff --help | grep -q color; then echo --color; else echo; fi)
-if [ "$#" -eq 0 ]; then
-	for variant in "${!variants_used[@]}"; do
-		sed '/^RUN[[:space:]]/d' "results/cur-$variant.list" | \
-			LC_COLLATE=C sort -r > "results/tmp.list"
-		mv "results/tmp.list" "results/cur-$variant.list"
+if grep -q '^FAIL[[:space:]]\+/' results.log; then
+	err "some tests failed"
+	grep '^FAIL[[:space:]]\+/' results.log >&2
 
-		if ! cmp -s "results/cur-$variant.list" "results/ref-$variant.list"; then
-			err "current results differ from reference"
-			diff $diffcolor -U1 "results/ref-$variant.list" "results/cur-$variant.list" >&2
-		fi
-	done
-
-	if [ -n "$TEST_PRINT_LOGS" -a -n "$failed" ]; then
+	if [ -n "$TEST_PRINT_LOGS" ]; then
 		echo -e "\nlogs of failed tests:" >&2
 		pushd logs >/dev/null
 		while read -r testname; do
 			[ -f "$testname.log" ] && grep -H . "$testname.log" >&2
-		done < <(sed 's%^FAIL[[:space:]]\+/%%p' ../results/cur-*.list)
+		done < <(sed 's%^FAIL[[:space:]]\+/%%p' < ../results.log)
 		popd >/dev/null
 	fi
+fi
 
-	if [ -f valgrind.log ] && grep -q 'ERROR SUMMARY: [1-9] errors' valgrind.log; then
-		err "found errors in valgrind.log"
-		if [ -n "$TEST_PRINT_LOGS" ]; then
-			echo -e "\nvalgrind.log:" >&2
-			cat valgrind.log >&2
-		fi
+if [ -f valgrind.log ] && grep -q 'ERROR SUMMARY: [1-9] errors' valgrind.log; then
+	err "found errors in valgrind.log"
+	if [ -n "$TEST_PRINT_LOGS" ]; then
+		echo -e "\nvalgrind.log:" >&2
+		cat valgrind.log >&2
 	fi
 fi
 
